### ISSUE TITLE
Images broken on website

### ISSUE THREAD

**Issue by arran4** [ViktorSvertoka/ViktorSvertoka#1]
![image](https://user-images.githubusercontent.com/111667/221708595-3a090ed6-c282-4eb5-bc76-f2033b5c96ba.png)

**Comment by arran4** [comment]
Also some don't work that well on dark mode:
![image](https://user-images.githubusercontent.com/111667/221708805-7a30b849-f26d-4b7a-bf1c-f479c9ce499a.png)

Because of transparent backgrounds.

**Comment by ViktorSvertoka** [comment]
Нello, I saw this problem, the icons are on the repository https://github.com/devicons
I think this is the problem...

**Comment by arran4** [comment]
Ah you have hot linked them..
`https://github.com/devicons/devicon/blob/master/icons/html5/html5-original-wordmark.svg`

Consider using a CDN however it looks like it has a JS / Font implementation so you shouldn't need to link *direct* to them at al! (But still will need a CDN)

![image](https://user-images.githubusercontent.com/111667/221722738-f777b8bf-7f21-4205-aaa3-d98d92bc262c.png)

Try:
`https://icongr.am/devicon/{icon}.svg?size={number}&color={hex}` 

Ie
`https://icongr.am/devicon/amazonwebservices-original.svg?size=128&color=currentColor`

Which might solve the issue I had with the dark theme too.

**Comment by ViktorSvertoka** [comment]
Thank you! For the solution, but unfortunately not all icons have a solution...( and as I see it, this is a global problem, not only me😅![image](https://user-images.githubusercontent.com/115661003/221951623-03147539-2d43-4b2b-96d1-0915b5c50bb4.png)![image](https://user-images.githubusercontent.com/115661003/221951659-d4842fa8-b1db-4e6a-9886-f10519d5f5b4.png)
